// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0_EJ-xceZeGY8YUb9ewqXbo-lYQspHQ',
    appId: '1:341419718777:web:f7c37c7cbdcaaf7d23fca8',
    messagingSenderId: '341419718777',
    projectId: 'pengelolaevent-bb1b3',
    authDomain: 'pengelolaevent-bb1b3.firebaseapp.com',
    storageBucket: 'pengelolaevent-bb1b3.firebasestorage.app',
    measurementId: 'G-V795RG97CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UcXHsRkIgZZ4NV3KjU08A6lSJVcKZgQ',
    appId: '1:341419718777:android:acfe82291404452323fca8',
    messagingSenderId: '341419718777',
    projectId: 'pengelolaevent-bb1b3',
    storageBucket: 'pengelolaevent-bb1b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjs8-vpU_amm1SaktAcGIkeTnZ0HlBfk',
    appId: '1:341419718777:ios:0654963110152b6f23fca8',
    messagingSenderId: '341419718777',
    projectId: 'pengelolaevent-bb1b3',
    storageBucket: 'pengelolaevent-bb1b3.firebasestorage.app',
    androidClientId: '341419718777-jn1bsce24cc34sk8drorfur1oo4ubs7v.apps.googleusercontent.com',
    iosClientId: '341419718777-hf3ok5g1og32p3ujlfu5m23c2c0tbtjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkjs8-vpU_amm1SaktAcGIkeTnZ0HlBfk',
    appId: '1:341419718777:ios:0654963110152b6f23fca8',
    messagingSenderId: '341419718777',
    projectId: 'pengelolaevent-bb1b3',
    storageBucket: 'pengelolaevent-bb1b3.firebasestorage.app',
    androidClientId: '341419718777-jn1bsce24cc34sk8drorfur1oo4ubs7v.apps.googleusercontent.com',
    iosClientId: '341419718777-hf3ok5g1og32p3ujlfu5m23c2c0tbtjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR0_EJ-xceZeGY8YUb9ewqXbo-lYQspHQ',
    appId: '1:341419718777:web:e3af0e927ed0042523fca8',
    messagingSenderId: '341419718777',
    projectId: 'pengelolaevent-bb1b3',
    authDomain: 'pengelolaevent-bb1b3.firebaseapp.com',
    storageBucket: 'pengelolaevent-bb1b3.firebasestorage.app',
    measurementId: 'G-FSJ4DDMM4J',
  );
}
